### ISSUE TITLE
Version listening idea

### ISSUE THREAD

**Issue by thecb4** [mxcl/Version#3]
Not sire if there is value here, but I've created a SemanticVersion framework that is focused on listening for changes and then updating the various places where you may have used the Semantic Version. The intent is for libraries where you have to list our your version in multiple places but only want to update it once.

https://gitlab.com/thecb4/SemVerSwift

Thoughts?

**Comment by mxcl** [comment]
I don’t really understand the usage. But either way, this library is a value type only and will not go beyond that. Thanks though.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mxcl** [comment]
Would like to understand the usage you are talking about better though.

**Comment by thecb4** [comment]
The use case is that I have various locations where I update the version of a piece of SW. ChangeLog, README, etc. I would a central place to update the version of a piece of SW and then as that version is updated, any subsequent files are updated as well.

example: SomeLibraryKit (supports, Carthage, Cocoa Pods, Swift Package Manager)
step: update version.yml file
step: automatically update CHANGELOG.md
step: automatically update podspec
step: automatically update README.md

each automatic update step represents a listener that does a regex for the Version and substitutes in the latest info.

**Comment by mxcl** [comment]
K I see, yeah this is outside the scope of this library. Though your thing would be a useful tool for continuous delivery IMO.

**Comment by thecb4** [comment]
Yes. That is my intent. I've been trying to find ways to automate a lot of those tasks using Swift just to see what's possible.
