### ISSUE TITLE
multiple targets named 'Tests' in: CryptoSwift, Version

### ISSUE THREAD

**Issue by acecilia** [mxcl/Version#8]
The actual `Tests` target is too generic, causing dependency name collisions that [SPM can not handle](https://forums.swift.org/t/multiple-target-issue-with-spm/16696). In this case, I found a collision between this package and https://github.com/krzyzanowskim/CryptoSwift.

After running `swift package generate-xcodeproj` the console shows the following error:
```
error: multiple targets named 'Tests' in: CryptoSwift, Version
```

The solution is to rename the target.

**Comment by mxcl** [comment]
1.1.2 is pushed.

**Comment by acecilia** [comment]
That was the fastest bugfix I have ever seen, I only had time to fork the repository before you closed the issue 😱 Thanks @mxcl

**Comment by mxcl** [comment]
https://mxcl.dev/canopy is the key.
